### ISSUE TITLE
Student count inconsistency

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/rails-layouts-and-templates#7]
https://learn.co/tracks/full-stack-web-dev-with-react says 193 students completed this lesson, but https://learn.co/tracks/full-stack-web-dev-with-react/rails/layouts-and-partials/layouts-and-templates-in-rails says 144 completed it

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like an improvement or fix to the Learn platform.
[Raising issues on
GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson)
should be reserved for problems with the curriculum itself (doesn't work,
throws a Ruby error, etc.)

Our product team loves to hear about our Learners' innovative interface
improvements. You can reach them at support@learn.co. Alternatively, if Learn
is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.
