### ISSUE TITLE
The Teaching is Unclear and Confusing

### ISSUE THREAD

**Issue by davidjkim810** [learn-co-curriculum/rails-layouts-and-templates#8]
Hello,

The teacher assumes that we know what the problem is before the foundations are not yet taught. This is a repeated theme through the teaching methods here.

Perhaps in the in-person school, the instructor walks through the basic method, THEN shows a problem to solve. For the online school, I feel like over and over again, there is the issue of jumping to a lab with little to no instruction. That runs the risk of learning things wrong. And I've had to assume a LOT of aspects of the teaching throughout the course so far and I've had to relearn things.

This is one of many examples.

"To find the generated layout, go and have a look in your Rails app at the following path. When you render a template for an action without specifying a different layout to use, Rails will use the layout found at this location: app/views/layouts/application.html.erb."

This is at the beginning of the lab. The teacher assumes we know how to render a template for an action.  It feels like the teacher is talking about the answer to multiplcation problems when the process of multiplication has not yet even been taught or shown. 

The labs are great and challenging. But the actual teaching via labs are for the most part unhelpful.
They aren't clear and because it is so wordy it is hard to identify what concepts are the most important.
I know that the objectives are there to help with that. But 9/10 the content is shown in an example before even being introduced.

I don't know if other online students have expresesed the same kind of issues. But this is just my feedback.

**Comment by morgvanny** [comment]
Sorry for any misunderstanding here - rendering templates for actions in rails is pretty thoroughly covered in the Intro to REST section, as well as the CRUD with Rails section. It's just referring to being able to serve up a view from any of the methods in a controller. In this particular instance, I don't think we're putting the cart before the horse, so to speak, but we are definitely on the lookout for places that is happening, and have been able to make some changes to smooth things out more.

Thanks for your feedback! I'll close this issue for now, but will keep an eye out if the wording here may be too unfamiliar with learners in the future.
